sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start Creating Docker image"
  - docker build -t mythdcom/docker-youtubeclone ./

script:
  - docker run -e CI=true mythdcom/docker-youtubeclone npm run test -- --coverage

after_success:
  - echo "Testing Complete"
