sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start Creating Docker image!"
  - docker build -t mythdcom/docker-youtubeclone ./

script:
  - echo "docker run -e CI=true imagename npm/yarn test -- --coverage but test module should exist"

after_success:
  - echo "Testing Complete"
